"""Render mappings.yml into a human-readable markdown lineage doc.
Used by the dashboard's Lineage tab and by docs/lineage.md."""
import os

import yaml

MAPPINGS_PATH = os.path.join(os.path.dirname(__file__), "..", "mappings.yml")


def render_markdown(spec: dict) -> str:
    lines = ["# FleetGuard Lineage\n", "Rendered from `mappings.yml`. Do not edit this file directly.\n"]
    for table_name, table in spec.get("tables", {}).items():
        lines.append(f"\n## `{table_name}`\n")
        if table.get("description"):
            lines.append(f"{table['description'].strip()}\n")
        if table.get("business_rule"):
            lines.append(f"**Business rule:** {table['business_rule'].strip()}\n")
        lines.append("| Target field | Source | Transformation |")
        lines.append("|---|---|---|")
        for f in table.get("fields", []):
            target = f.get("target_field", "")
            source = f.get("source", "").strip()
            transform = " ".join(f.get("transform", "").split())
            lines.append(f"| `{target}` | {source} | {transform} |")
    return "\n".join(lines) + "\n"


def load_spec():
    with open(MAPPINGS_PATH) as f:
        return yaml.safe_load(f)


def main():
    spec = load_spec()
    md = render_markdown(spec)
    out_path = os.path.join(os.path.dirname(__file__), "..", "docs")
    os.makedirs(out_path, exist_ok=True)
    with open(os.path.join(out_path, "lineage.md"), "w") as f:
        f.write(md)
    print(f"Wrote {os.path.join(out_path, 'lineage.md')}")


if __name__ == "__main__":
    main()
